module.exports = [

		{name: `Flatiron Pepper Co "I Can't Feel My Face" Pepper Flakes`, 
			image: "./images/flatironpepper.jpg", 
			link: "https://www.flatironpepper.com/collections/frontpage/products/i-cant-feel-my-face",
			sortPrice: 20,
			listPrice: "$20 + s&h",
			quote: "What can I say? I like some spice with my food."},
		{name: `Lace Lab Red Flat Shoe Laces (63")`, 
			image: "./images/lacelabred.jpg", 
			link: "https://www.lacelab.com/collections/flat-laces/products/red-shoe-laces?variant=7899986693",
			sortPrice: 5,
			listPrice: "$5 + s&h",
			quote: "Sometimes it's nice to mix things up with a custom option."},
		{name: `Dinner at Sushi Taku`, 
			image: "./images/sushitaku.jpg", 
			link: "http://www.sushitaku.com",
			sortPrice: 33,
			listPrice: "~$33/person (after tax & tip)",
			quote: "I'd eat here every night if I could afford that much mercury."},
		{name: `Apple iPhone 7 Plus Leather Case (Black)`, 
			image: "./images/iphonecase.jpg", 
			link: "https://www.apple.com/shop/product/MQHJ2ZM/A/iphone-8-plus-7-plus-leather-case-taupe?fnode=99&fs=f%3Diphone7plus%26fh%3D458b%252B47e1",
			sortPrice: 49,
			listPrice: "$49",
			quote: "Let's just say the phone has outlived the case."},
		{name: `Pyritized Ammonite`, 
			image: "./images/ammonite.jpg", 
			link: "https://davesrockshop.com/pyritized-ammonites-holzmaden-germany.html",
			sortPrice: 62.5,
			listPrice: "$62.50",
			quote: "It's a fossil made from fool's gold. How awesome is that?"},
		{name: `Stance Socks Star Wars Duos 4 Pack (Large)`, 
			image: "./images/stancesw.jpg", 
			link: "https://www.ebay.com/itm/Stance-NEW-Unisex-Star-Wars-Duos-4-Pack-Socks-Multi-BNWT/254399781541?hash=item3b3b689aa5:m:mr8LgANaxH8nVV3RC1_QxOQ&var=553998741878",
			sortPrice: 85,
			listPrice: "~$85 + s&h",
			quote: "You wouldn't have to Force me to put a pair of these on my feet."},
		{name: `Stainless Steel Liquor Pour Spouts`, 
			image: "./images/spouts.jpg", 
			link: "https://www.amazon.com/Liquor-Pour-Spouts-Set-Stainless/dp/B01LW2L7R9",
			scrape: true,
			quote: "Take two cocktail-making classes and suddenly you're everyone's bartender..."},
		{name: `Buffalo Wild Wings Mango Habanero Sauce`, 
			image: "./images/bwwmango.jpg", 
			link: "https://www.amazon.com/Buffalo-Wild-Wings-Sauce-Habanero/dp/B00D4XNNCM",
			scrape: true,
			quote: "Everything tastes better with mango habanero!"},
		{name: `KitchenAid Pasta Roller Set`, 
			image: "./images/roller.jpg", 
			link: "https://www.amazon.com/KitchenAid-KSMPRA-3-Piece-Roller-Attachment/dp/B01DBGQR1K",
			scrape: true,
			quote: "See what I did there?"},
		{name: `Air Max 1 Tinker Sketch to Shelf Black (Size 10)`, 
			image: "./images/airmaxtinker.jpg", 
			link: "https://stockx.com/nike-air-max-1-tinker-sketch-to-shelf-black",
			size: 10,
			scrape: true,
			quote: 	`They're like wearing an episode of "How It's Made".`},
		{name: `Nintendo Switch`, 
			image: "./images/switch.jpg", 
			link: "https://www.amazon.com/Nintendo-Switch-Neon-Blue-Joy%E2%80%91/dp/B07VGRJDFY",
			scrape: true,
			quote: "Help me resdiscover the bittersweet joy of playing games on a handheld console until it's suddenly 5am on a weeknight."},
		{name: `4D Runner Pharrell Tech Olive (Size 9.5)`, 
			image: "./images/4dpharrell.jpg", 
			link: "https://stockx.com/adidas-4d-runner-pharrell-tech-olive",
			size: 9.5,
			scrape: true,
			quote: "3D printed shoes are the future, and Pharrell picked a nice green."},
		{name: `Jordan 1 Retro High Union Los Angeles Blue Toe (Size 9.5)`, 
			image: "./images/unionblue.jpg", 
			link: "https://stockx.com/air-jordan-1-retro-high-union-los-angeles-blue-toe",
			size: 9.5,
			scrape: true,
			quote: "Classic silhouette with a radical twist."},
		{name: `Carlisle CC Rack & Pinion Mount Flameworking Torch`, 
			image: "./images/carlislecc.jpg", 
			link: "https://www.mountainglass.com/Carlisle-CC-Rack-Pinion-Mount-4-Inlet-5-Centerfire",
			sortPrice: 1544,
			listPrice: "$1544 + s&h",
			quote: `The most important tool I'm missing to create more art like <a href="https://alex.berez.com/glass" target="blank"">this</a>.`},
		{name: `LEGO Imperial Star Destroyer`, 
			image: "./images/destroyer.jpg", 
			link: "https://www.lego.com/en-us/product/imperial-star-destroyer-75252",
			sortPrice: 700,
			listPrice: "$700",
			quote: "Yes, it's almost 4 feet long. No, I don't have anywhere to put it. Why do you ask?"},
		{name: `Rishadan Port Print`, 
			image: "./images/port.jpg", 
			link: "https://www.ebay.com/itm/MTG-Magic-Mercadian-Masques-Rishadan-Port-Print-Giclee-by-SIGNED-Jerry-Tiritilli-/392297863191",
			sortPrice: 50,
			listPrice: "$50 + s&h",
			quote: "One of my favorite pieces of art in the entire game of Magic: the Gathering."},
		{name: `Dark Ritual Print`, 
			image: "./images/darkrit.jpg", 
			link: "https://rebeccaguaymtgartstore.weebly.com/store/p60/Dark_Ritual.html",
			sortPrice: 90,
			listPrice: "$90",
			quote: "An iconic artist's take on an iconic Magic: the Gathering card."},
		{name: `Brandon Sanderson Leather-bound Book (Any Title)`, 
			image: "./images/leatherbook.jpg", 
			link: "https://store.brandonsanderson.com/search.php?mode=1&search_query_adv=leather-bound%20book&brand=&searchsubs=ON&price_from=100&price_to=100&featured=&shipping=&category%5B%5D=19&section=product",
			sortPrice: 100,
			listPrice: "$100 + s&h",
			quote: "If I'm going to fill my library with fancy leather books, I'm starting with the works of my favorite author."},
		{name: `Canadian $4 Fossilized Tyrannosaurus Rex Silver Coin`, 
			image: "./images/silvertrex.jpg", 
			link: "https://www.colonialacres.com/product-p/623429.htm",
			sortPrice: 50,
			listPrice: "$50 + s&h",
			quote: "Precious metals and dinosaurs: a timeless combination."},
		{name: `Marabou Daim Chocolate Bar`, 
			image: "./images/maraboudaim.jpg", 
			link: "https://www.amazon.com/Marabou-Daim-Milk-Chocolate-King/dp/B00642BRGY",
			scrape: true,
			quote: "The secret ingredient in the best chocolate chip cookies you'll ever taste."},
		{name: `Nike Adapt BB Mag (Size 10)`, 
			image: "./images/bbmag.jpg", 
			link: "https://stockx.com/nike-adapt-bb-mag",
			size: 9.5,
			scrape: true,
			quote: "The closest thing to a functional pair of <i>Back to the Future II</i>'s Nike Air Mags this side of $30,000."},
		{name: `Ultra Boost 2020 ISS US National Lab Dash Grey (Size 9.5)`, 
			image: "./images/issultraboost.jpg", 
			link: "https://stockx.com/adidas-ultra-boost-2020-iss-us-national-lab-dash-grey",
			size: 9.5,
			scrape: true,
			quote: "Shiny. Space. Shoes."},
		{name: `Air Mag Slippers`, 
			image: "./images/magslippers.jpg", 
			link: "https://bannedgoods.com/collections/view-all/products/mags",
			sortPrice: 60,
			listPrice: "$60 + s&h",
			quote: "Not your average pair of slippers."},
		{name: `Copper Gnome Cocktail Shaker`, 
			image: "./images/gnomeshaker.jpg", 
			link: "https://www.williams-sonoma.com/products/elyx-copper-gnome-cocktail-shaker/?pkey=ctabletop-bar-tool%7Cbar-cocktail-shaker",
			sortPrice: 100,
			listPrice: "$100",
			quote: "The best way to make drinks is in a high-end lawn ornament."},
	]

/* Gift Templates

Scrape Amazon: 

		{name: ``, 
			image: "./images/", 
			link: "",
			scrape: true,
			quote: ""},

Scrape StockX: 

		{name: ``, 
			image: "./images/", 
			link: "",
			size: ,
			scrape: true,
			quote: ""},

No Scrape: 

		{name: ``, 
			image: "./images/", 
			link: "",
			sortPrice: ,
			listPrice: "",
			quote: ""},

*/