module.exports = [

		{name: `Flatiron Pepper Co "I Can't Feel My Face" Pepper Flakes`, 
			image: "./images/flatironpepper.jpg", 
			link: "https://www.flatironpepper.com/collections/frontpage/products/i-cant-feel-my-face",
			sortPrice: 20,
			listPrice: "$20 + s&h"},
		{name: `Lace Lab Red Flat Shoe Laces (63")`, 
			image: "./images/lacelabred.jpg", 
			link: "https://www.lacelab.com/collections/flat-laces/products/red-shoe-laces?variant=7899986693",
			sortPrice: 5,
			listPrice: "$5 + s&h"},
		{name: `Dinner at Sushi Taku`, 
			image: "./images/sushitaku.jpg", 
			link: "http://www.sushitaku.com",
			sortPrice: 33,
			listPrice: "~$33/person (after tax & tip)"},
		{name: `Apple iPhone 7 Plus Leather Case (Black)`, 
			image: "./images/iphonecase.jpg", 
			link: "https://www.apple.com/shop/product/MQHJ2ZM/A/iphone-8-plus-7-plus-leather-case-taupe?fnode=99&fs=f%3Diphone7plus%26fh%3D458b%252B47e1",
			sortPrice: 49,
			listPrice: "$49"},
		{name: `Pyritized Ammonite`, 
			image: "./images/ammonite.jpg", 
			link: "https://davesrockshop.com/pyritized-ammonites-holzmaden-germany.html",
			sortPrice: 62.5,
			listPrice: "$62.50"},
		{name: `Stance Socks Star Wars Duos 4 Pack (Large)`, 
			image: "./images/stancesw.jpg", 
			link: "https://www.ebay.com/itm/Stance-NEW-Unisex-Star-Wars-Duos-4-Pack-Socks-Multi-BNWT/254399781541?hash=item3b3b689aa5:m:mr8LgANaxH8nVV3RC1_QxOQ&var=553998741878",
			sortPrice: 85,
			listPrice: "~$85 + s&h"},
		{name: `Stainless Steel Liquor Pour Spouts`, 
			image: "./images/spouts.jpg", 
			link: "https://www.amazon.com/Liquor-Pour-Spouts-Set-Stainless/dp/B01LW2L7R9?th=1",
			sortPrice: 10,
			listPrice: "$10"},
		{name: `Buffalo Wild Wings Mango Habanero Sauce`, 
			image: "./images/bwwmango.jpg", 
			link: "https://www.amazon.com/Buffalo-Wild-Wings-Sauce-Habanero/dp/B00D4XNNCM",
			sortPrice: 13.5,
			listPrice: "$13.50"},
		{name: `KitchenAid Pasta Roller Set`, 
			image: "./images/roller.jpg", 
			link: "https://www.amazon.com/KitchenAid-KSMPRA-3-Piece-Roller-Attachment/dp/B01DBGQR1K",
			sortPrice: 139,
			listPrice: "$139"},
		{name: `Air Max 1 Tinker Sketch to Shelf Black (Size 10)`, 
			image: "./images/airmaxtinker.jpg", 
			link: "https://stockx.com/nike-air-max-1-tinker-sketch-to-shelf-black",
			size: 10,
			scrape: true},
		{name: `Nintendo Switch`, 
			image: "./images/switch.jpg", 
			link: "https://www.amazon.com/Nintendo-Switch-Neon-Blue-Joy%E2%80%91/dp/B07VGRJDFY/ref=sr_1_1?keywords=nintendo%2Bswitch&qid=1577222266&sr=8-1&th=1",
			sortPrice: 299,
			listPrice: "$299"},
		{name: `4D Runner Pharrell Tech Olive (Size 10)`, 
			image: "./images/4dpharrell.jpg", 
			link: "https://stockx.com/adidas-4d-runner-pharrell-tech-olive",
			size: 10,
			scrape: true},
		{name: `Jordan 1 Retro High Union Los Angeles Blue Toe (Size 9.5)`, 
			image: "./images/unionblue.jpg", 
			link: "https://stockx.com/air-jordan-1-retro-high-union-los-angeles-blue-toe",
			size: 9.5,
			scrape: true},
		{name: `Carlisle CC Rack & Pinion Mount Flameworking Torch`, 
			image: "./images/carlislecc.jpg", 
			link: "https://www.mountainglass.com/Carlisle-CC-Rack-Pinion-Mount-4-Inlet-5-Centerfire",
			sortPrice: 1544,
			listPrice: "$1544 + s&h"},
		{name: `LEGO Imperial Star Destroyer`, 
			image: "./images/destroyer.jpg", 
			link: "https://www.lego.com/en-us/product/imperial-star-destroyer-75252",
			sortPrice: 700,
			listPrice: "$700"},
		{name: `Rishadan Port Print`, 
			image: "./images/port.jpg", 
			link: "https://www.ebay.com/itm/MTG-Magic-Mercadian-Masques-Rishadan-Port-Print-Giclee-by-SIGNED-Jerry-Tiritilli-/392297863191",
			sortPrice: 40,
			listPrice: "$40 + s&h"},
		{name: `Dark Ritual Print`, 
			image: "./images/darkrit.jpg", 
			link: "https://rebeccaguaymtgartstore.weebly.com/store/p60/Dark_Ritual.html",
			sortPrice: 90,
			listPrice: "$90"},
		{name: `Brandon Sanderson Leather-bound Book (Any Title)`, 
			image: "./images/leatherbook.jpg", 
			link: "https://store.brandonsanderson.com/search.php?mode=1&search_query_adv=leather-bound%20book&brand=&searchsubs=ON&price_from=100&price_to=100&featured=&shipping=&category%5B%5D=19&section=product",
			sortPrice: 100,
			listPrice: "$100 + s&h"},
		{name: `Canadian $4 Fossilized Tyrannosaurus Rex Silver Coin`, 
			image: "./images/silvertrex.jpg", 
			link: "https://www.cdncoin.com/product-p/623932234291.htm",
			sortPrice: 60,
			listPrice: "$60 + s&h"},
		{name: `Marabou Daim Chocolate Bar`, 
			image: "./images/maraboudaim.jpg", 
			link: "https://www.amazon.com/Marabou-Daim-Milk-Chocolate-King/dp/B00642BRGY",
			sortPrice: 7.5,
			listPrice: "$7.50"},
		{name: `Jordan 1 Retro High Spider-Man Origin Story (Size 9.5)`, 
			image: "./images/spidermanj1.jpg", 
			link: "https://stockx.com/air-jordan-1-retro-high-chicago-crystal?size=9.5",
			size: 9.5,
			scrape: true},
		{name: `Ultra Boost 2020 ISS US National Lab Tech Indigo (Size 10)`, 
			image: "./images/issultraboost.jpg", 
			link: "https://stockx.com/adidas-ultra-boost-2020-iss-us-national-lab-tech-indigo",
			size: 10,
			scrape: true},
	]

/* Gift Templates

Scrape: 

		{name: ``, 
			image: "./images/", 
			link: "",
			size: ,
			scrape: true},

No Scrape: 

		{name: ``, 
			image: "./images/", 
			link: "",
			sortPrice: ,
			listPrice: ""},

*/